strategies:
  ma_cross_over:
    module: app.strategy.ma_cross.MaCrossStrategy

indicators:
  ma:
    module: app.indicator.ma.MaCalculator
  adx:
    module: app.indicator.adx.AdxCalculator


exchange:
  mode: ccxt               # ccxt=ccxt.pro (spot testnet / 实盘)
  name: binance
  proxy: ""                 # 直连，无需代理
  sandbox: true             # true=spot testnet, false=实盘
  api_key: "hEgpUwEBaNcUbS2bJEh3vhRKeu1CKfQN4Y5flCLVPKU2CE1BoVhKXZxiQDjrPJ5Z"
  api_secret: "RkicnxgvRd9UPUJoj7bKEJaY4iPMNuDqJgnBE4iZqMiVLVMC7KIjOXziRCNRRpYQ"

channel:
  BTC/USDT:
    market: spot
    allocation: 0.3
    intervals:
      1m:
        strategy:
          name: ma_cross_over
          params: { fast: 5, slow: 20 }
          indicators:
            - name: ma
              params: { periods: [5, 20] }
            - name: adx
              params: { period: 14 }
        risk_pre:  { daily_loss_limit: 500, max_drawdown: 0.08 }
        risk_post: { max_per_order_ratio: 0.1, max_leverage: 20 }
